/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/common/Badge.vue')['default']
    Cropper: typeof import('./src/components/common/ImageCropUploader/Cropper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Iconfont: typeof import('./src/components/common/Iconfont.vue')['default']
    ImageCropUploader: typeof import('./src/components/common/ImageCropUploader/index.vue')['default']
    MarkdownEditor: typeof import('./src/components/common/MarkdownEditor.vue')['default']
    MarkdownPreview: typeof import('./src/components/common/MarkdownPreview.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./src/components/common/Tab.vue')['default']
    TabNav: typeof import('./src/components/common/TabNav.vue')['default']
    Webview: typeof import('./src/components/common/Webview.vue')['default']
  }
}
